Repository openshift/logging-view-plugin, pull requests merged in 2023-08, with the labels that each got.

#130 OCPBUGS-14902: Loki search does not allow special chars
  web/cypress/integration/logs-page.cy.ts
  web/src/__tests__/attribute-filters.spec.ts
  web/src/attribute-filters.tsx
Labels: jira/valid-bug, lgtm, approved, jira/valid-reference

#131 Check previous vs. current cluster endpoint for creation of env vars
  web/scripts/start-console.sh
Labels: lgtm, approved

#132 LOG-4429: filter alerting rules tenant based on namespace
  web/src/getAlertingRules.ts
  web/src/value-utils.ts
Labels: lgtm, approved, jira/valid-reference

#133 LOG-4439: Initialize filters from url
  web/src/hooks/useURLState.ts
Labels: lgtm, approved, jira/valid-reference

#135 LOG-4465: Display correct message if logQL expression has line formatting
  web/cypress/fixtures/query-range-fixtures.ts
  web/cypress/integration/logs-page.cy.ts
  web/src/components/logs-table.tsx
Labels: lgtm, approved, jira/valid-reference

#137 OU-239: Add all team members to all repo's OWNERS
  OWNERS
Labels: lgtm, approved, jira/valid-reference
