Repository openshift/logging-view-plugin, pull requests merged in 2024-06, with the labels that each got.

#192 LOG-5287: Update the Admin > Logs page to pull the available pod list from the Loki API
  web/src/attribute-filters.tsx
  web/src/pages/logs-dev-page.tsx
  web/src/pages/logs-page.tsx
Labels: lgtm, approved, jira/valid-reference

#193 Fix logging-view-plugin-resources.yml
  logging-view-plugin-resources.yml
Labels: ok-to-test, lgtm, approved

#191 fix: typos in configuration parameters
  README.md
  pkg/server/server.go
  web/locales/en/plugin__logging-view-plugin.json
  web/src/components/error-message.tsx
Labels: lgtm, approved

#195 OU-456: Add CSRF header on POST requests to avoid proxy filter
  web/src/cancellable-fetch.ts
Labels: lgtm, approved, jira/valid-reference

#194 [release-5.7] LOG-5032: backport korrel8r client to get links from alerts to logs
  web/src/hooks/useLogActionsExtension.tsx
  web/src/korrel8r-client.ts
  web/src/korrel8r.types.ts
Labels: lgtm, approved, jira/valid-reference
