Repository openshift/logging-view-plugin, pull requests merged in 2024-08, with the labels that each got.

#207 OU-483: Add the Volume API to the Logging-View-Plugin
  hack/docker-compose/docker-compose.test.yml
  hack/docker-compose/loki/loki-config.yml
  web/cypress/fixtures/query-range-fixtures.ts
  web/cypress/integration/logs-page.cy.ts
  web/locales/en/plugin__logging-view-plugin.json
  web/src/components/execute-volume-button.tsx
  web/src/components/logs-metrics.tsx
  web/src/components/logs-query-input.css
  web/src/components/logs-query-input.tsx
  web/src/components/logs-toolbar.tsx
  web/src/hooks/useLogs.ts
  web/src/logs.types.ts
  web/src/loki-client.ts
  web/src/pages/logs-detail-page.tsx
  web/src/pages/logs-dev-page.tsx
  web/src/pages/logs-page.tsx
  web/src/test-ids.ts
Labels: lgtm, approved, jira/valid-reference

#211 COO-288: make correlation links aware of dev perspective
  web/mockModules/dummy.tsx
  web/src/components/logs-table.tsx
  web/src/hooks/useLogActionsExtension.tsx
Labels: qe-approved, lgtm, approved, jira/valid-reference

#214 Fix Refresh Button to Follow PatternFly Guidelines
  web/src/pages/logs-detail-page.tsx
  web/src/pages/logs-dev-page.tsx
  web/src/pages/logs-page.tsx
Labels: lgtm, approved

#216 NO-JIRA: Update go mod for midstream and Dockerfile.dev
  go.mod
Labels: lgtm, approved, jira/valid-reference
